name: 'Action Validate Deploy Date'
description: 'Validation Deploy'
inputs: 
  domain:
    description: 'domain jira'
    required: true
  basic-auth:
    description: 'jira authentication'
    required: true  
outputs:
  result:
    description: 'finished process'
runs:
  using: 'node16'
  main: 'dist/index.js'