name: release and changelog
on:
  push:
    branches:
      - production

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: release
        uses: madeiramadeirabr/action-generate-release@production
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
